export {default as Foo} from './foo'
export {default as ServicePage} from './service'
export {default as HomePage} from './home'
export {default as LoginPage} from './login'
export {default as RegisterPage} from './register'